### ISSUE TITLE
I want to remove the normal colored frame

### ISSUE THREAD

**Issue by Hatem-Jr** [colinlaney/animal-tracking#15]
Hi,
1- I want to make a modification and only show the "frameGray" in both the drawing of the cropping polygon at the beginning and the analysis phase, I tried to remove "frame" from line 133: imgFloorCorners = np.hstack([frame,frameGray]) and it worked in the cropping phase but when it came time to processing the video it didn't even begin:
![Screenshot 2021-07-09 142951](https://user-images.githubusercontent.com/47870128/125078215-618f7180-e0c2-11eb-87c7-0751fe26d29b.png)
![Screenshot 2021-07-09 143116](https://user-images.githubusercontent.com/47870128/125078228-6522f880-e0c2-11eb-8f32-cfd0ddc5f994.png)

2-There was a previous issue that I made about a GUI I made (a demo one) and I forked my repo can you look at it ?

Thanks :)

**Comment by colinlaney** [comment]
Have you succeeded with your video file early, before the elimination of `np.hstack`? Have you googled the output message? I'm asking because the error looks like has nothing to do with the code. The problem is either with the presence of an audio stream or with non-conventional file name.

Please let me know what was that.
