### ISSUE TITLE
Code not running properly

### ISSUE THREAD

**Issue by Cruz1946** [colinlaney/animal-tracking#22]
Hi! Thank you again for all the help till now. I run the code and it lets me select the ROI, but when i press space ou enter to confirm the window just vanishes. On the console i can see the code running, but it doesnt do anything.

**Comment by colinlaney** [comment]
Try to reduce the resolution of your video first. The [sample video](https://github.com/colinlaney/animal-tracking/blob/b5572529176c4a5467421780111d060832c84f70/rat.avi) is 600p, [1080p](https://github.com/colinlaney/animal-tracking/issues/20#issue-1731387736) might be too much for your GPU/CPU, so you couldn't wait for the processing to begin. I can't hypothesize smarter without more input.

May I close #20 and #21?

**Comment by Cruz1946** [comment]
Yes you may close those ones.

I'd really like to know the way you select your mice to do the tracking,
because i have a code of my own and it sometimes works fine except when
the tracker gets lost. Im using an CSRT tracker, but surely its not the
best way to track a mice since he moves his body on many directions. Im
sorry to be bothering you so much lately, but i dont have much support of
my project coordinator.

Best regards,
Rafael Cruz

colinlaney ***@***.***> escreveu no dia domingo, 11/06/2023
à(s) 00:08:

**Comment by colinlaney** [comment]
CSRT is a learnable method that shows great results when object is overlapped by others, meanwhile, it is unstable when the object is lost for a long time (your case?) as well as my method. There are many [other methods in OpenCV](https://broutonlab.com/blog/opencv-object-tracking), try them as well.

My method is not learnable. Most of the code is serving the user interface whereas the idea is as straightforward as possible.

Since color and light conditions are controllable, all the core do is
1. [Differentiates](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L202-L203) a light area from a dark area by the [threshold](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L11). In the most contrast case, the mice were white, the floor was glossy black, so the light area is either the mouse or reflections of the light source
2. Gets the [biggest spot](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L207-L208), assuming it is a mouse
3. [Looks for the center of mass](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L209-L213) of the spot to
4. [track this very point](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L204-L217).

If you are familiar with Python and have a GPU, use [Detectron](https://github.com/facebookresearch/detectron2), or [Yolo](https://github.com/WongKinYiu/yolov7), or other state-of-the-art object detectors.

**Comment by Cruz1946** [comment]
I ended up using a threshold method also. But i had to edit my video since
the mice was black.  Thank you for the suggestions to use yolo. I'll try
them next, since my project is supose to be about deep learning. Thank you
for all your help till now, you may close all our chats.
Best regards

A terça, 13/06/2023, 18:22, colinlaney ***@***.***> escreveu:
