### ISSUE TITLE
Open field test for circular arena

### ISSUE THREAD

**Issue by ghost** [colinlaney/animal-tracking#5]
I'm interested in assessing the behaviour of animals by open field test in a circular arena.Is it possible to track their movements using animal-tracking in a circular arena? It would also be useful in Morris Water Maze.

**Comment by colinlaney** [comment]
I guess current version will misdetect the "floor", but **you are free to fit the area** of arena by bounding box using mouse pointer. Please try it and reopen the Issue in case of errors.

And remember that _an animal must be as contrast as possible_ to water color of the maze. I'm planning to replace object detector with [Yolo](https://arxiv.org/abs/1612.08242) since current version of detector is written in old-school style and is extremely unstable.
